# Generated by Django 3.1.4 on 2020-12-18 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tag_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tagclass')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('png', models.FileField(upload_to='')),
                ('pdf', models.FileField(upload_to='')),
                ('tags', models.ManyToManyField(to='portal.Tag')),
            ],
        ),
    ]
