# Generated by Django 3.1.6 on 2021-02-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210106_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(default='failed.pdf', max_length=262, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='png',
            field=models.FileField(max_length=262, upload_to=''),
        ),
    ]
