# Generated by Django 4.0.1 on 2022-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210202_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagClass',
        ),
    ]
