# Generated by Django 3.1.4 on 2020-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='tags',
            field=models.ManyToManyField(to='codestudy.Tag'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
