# Generated by Django 3.1.4 on 2020-12-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('given_name', models.TextField()),
                ('family_name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(default='failed.pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='png',
            field=models.FileField(default='failed.png', upload_to=''),
        ),
    ]
