# Generated by Django 3.1.4 on 2020-12-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestudy', '0002_auto_20201216_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('png', models.FileField(upload_to='')),
                ('pdf', models.FileField(upload_to='')),
                ('tags', models.ManyToManyField(to='codestudy.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
