# Generated by Django 3.1.4 on 2020-12-30 11:06

import codestudy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestudy', '0003_user_can_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_edit',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'STANDARD'), (2, 'EDITOR'), (3, 'ADMIN')], default=codestudy.models.UserType['STANDARD']),
        ),
    ]
