# Generated by Django 3.1.4 on 2020-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestudy', '0003_auto_20201216_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='description',
            field=models.TextField(default='jtjteiur'),
            preserve_default=False,
        ),
    ]
